site_name: MkDocs テンプレート
site_url: https://zu-min-g.github.io/template-mkdocs/
theme:
  language: 'ja'
  name: 'material'
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 暗くする
      primary: indigo
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 明るくする
      primary: indigo
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - footnotes
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  - https://d3js.org/d3.v6.min.js
  - assets/javascripts/extra.js
